development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL_ENV_MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_ENV_MYSQL_USER'] %>
  password: <%= ENV['MYSQL_ENV_MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  port: 3306

test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL_ENV_MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_ENV_MYSQL_USER'] %>
  password: <%= ENV['MYSQL_ENV_MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  port: 3306